/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.alejnp.ugr.dsd.donaciones;

import java.io.Serializable;
import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.Map;

public class ServidorNodo implements Servicio, Serializable {
    private static final long serialVersionUID = 7696533861965512717L;

	private final Map<String, Double> transacciones = new HashMap<>();

    @Override
    public boolean registrar(String nombreCliente) throws RemoteException {
        return transacciones.putIfAbsent(nombreCliente, 0.) == null;
    }

    @Override
    public boolean donar(String nombreCliente, Double cantidad) throws RemoteException {
        // return !transacciones.containsKey(nombreCliente) &&
            // transacciones.merge(nombreCliente, cantidad, Double::sum) != null;

        if(!transacciones.containsKey(nombreCliente)) {
            return false;
        }

        return transacciones.merge(nombreCliente, cantidad, Double::sum) != null;
    }

    @Override
    public double consultar() throws RemoteException {
        return transacciones.values()
            .stream()
            .mapToDouble(Double::valueOf)
            .sum();
    }

    @Override
    public boolean existe(String nombreCliente) throws RemoteException {
        return transacciones.containsKey(nombreCliente);
    }
}
