/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.alejnp.ugr.dsd.donaciones;

import java.rmi.Remote;
import java.rmi.RemoteException;

public interface Servicio extends Remote {
  boolean registrar(String nombreCliente) throws RemoteException;
  boolean existe(String nombreCliente) throws RemoteException;
  boolean donar(String nombreCliente, Double cantidad) throws RemoteException;
  double consultar() throws RemoteException;
  double consultar(String nombreCliente) throws RemoteException;
}